language: go
go:
    - 1.9
    - master
before_install:
    - go get golang.org/x/tools/cmd/cover
    - go get github.com/mattn/goveralls
sccript:
    - go test -v ./...
    - $HOME/gopath/bin/goveralls -service=travis-ci
